name: bridge
on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/bridge.yml'
      - 'bridge/**'
      - '!**/*.md'
  pull_request:
    paths:
      - '.github/workflows/bridge.yml'
      - 'bridge/**'
      - '!**/*.md'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  tests:
    if: |
      ${{ github.event_name == 'pull_request' }}
    timeout-minutes: 15
    runs-on: ubuntu-latest
    name: 'Test bridge'

    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@a90bcbc6539c36a85cdfeb73f7e2f433735f215b # v2.15.0
        with:
          egress-policy: audit

      - name: Checkout csolution-rpc repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6.2.0
        with:
          node-version: 'lts/*'

      - name: Install dependencies
        run: npm ci
        working-directory: bridge

      - name: Run linter
        run: npm run lint
        working-directory: bridge
