name: bridge
on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/bridge.yml'
      - 'bridge/**'
      - '!**/*.md'
  pull_request:
    paths:
      - '.github/workflows/bridge.yml'
      - 'bridge/**'
      - '!**/*.md'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  tests:
    if: |
      ${{ github.event_name == 'pull_request' }}
    timeout-minutes: 15
    runs-on: ubuntu-latest
    name: 'Test bridge'

    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411 # v2.19.4
        with:
          egress-policy: audit

      - name: Checkout csolution-rpc repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version: 'lts/*'

      - name: Install dependencies
        run: npm ci
        working-directory: bridge

      - name: Run linter
        run: npm run lint
        working-directory: bridge
