name: codegen
on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/codegen.yml'
      - 'codegen/**'
      - '!**/*.md'
  pull_request:
    paths:
      - '.github/workflows/codegen.yml'
      - 'codegen/**'
      - '!**/*.md'
  release:
    types: [published]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    if: |
      ${{ github.event_name == 'pull_request' || github.event_name == 'release' }}
    timeout-minutes: 15
    runs-on: ubuntu-latest
    name: 'Test codegen'

    steps:
      - name: Checkout csolution-rpc repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'

      - name: Install dependencies
        run: npm ci
        working-directory: codegen

      - name: Run linter
        run: npm run lint
        working-directory: codegen

      - name: Run tests
        run: npm test
        working-directory: codegen

      - name: Archive test report
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: codegen-test
          path: codegen/reports/junit/testreport.xml
          retention-days: 1
          if-no-files-found: error
      
      - name: Archive generated interface files
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: codegen-rpc-interfaces
          path: codegen/generated/*
          retention-days: 1
          if-no-files-found: error

  release:
    if: ${{ github.event_name == 'release' }}
    needs: [ tests ]
    timeout-minutes: 15
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Download generated files
        uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4.3.0
        with:
          name: codegen-rpc-interfaces
          path: generated

      - name: Zip generated files
        run: zip -r csolution-rpc.zip *
        working-directory: generated

      - name: Attach files to release assets
        id: release_assets
        uses: svenstaro/upload-release-action@04733e069f2d7f7f0b4aebc4fbdbce8613b03ccd # v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: generated/csolution-rpc.zip
          tag: ${{ github.ref }}
          overwrite: true
          asset_name: csolution-rpc.zip
